# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Basys3_XDC/MY_Basys-3-Master.xdc

# Block Designs: bd/design_MicroBlazeButton/design_MicroBlazeButton.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MicroBlazeButton || ORIG_REF_NAME==design_MicroBlazeButton} -quiet] -quiet

# IP: bd/design_MicroBlazeButton/ip/design_MicroBlazeButton_microblaze_0_0/design_MicroBlazeButton_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MicroBlazeButton_microblaze_0_0 || ORIG_REF_NAME==design_MicroBlazeButton_microblaze_0_0} -quiet] -quiet

# IP: bd/design_MicroBlazeButton/ip/design_MicroBlazeButton_axi_uartlite_0_0/design_MicroBlazeButton_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MicroBlazeButton_axi_uartlite_0_0 || ORIG_REF_NAME==design_MicroBlazeButton_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/design_MicroBlazeButton/ip/design_MicroBlazeButton_axi_gpio_0_0/design_MicroBlazeButton_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MicroBlazeButton_axi_gpio_0_0 || ORIG_REF_NAME==design_MicroBlazeButton_axi_gpio_0_0} -quiet] -quiet

# IP: bd/design_MicroBlazeButton/ip/design_MicroBlazeButton_dlmb_v10_0/design_MicroBlazeButton_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MicroBlazeButton_dlmb_v10_0 || ORIG_REF_NAME==design_MicroBlazeButton_dlmb_v10_0} -quiet] -quiet

# IP: bd/design_MicroBlazeButton/ip/design_MicroBlazeButton_ilmb_v10_0/design_MicroBlazeButton_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MicroBlazeButton_ilmb_v10_0 || ORIG_REF_NAME==design_MicroBlazeButton_ilmb_v10_0} -quiet] -quiet

# IP: bd/design_MicroBlazeButton/ip/design_MicroBlazeButton_dlmb_bram_if_cntlr_0/design_MicroBlazeButton_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MicroBlazeButton_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_MicroBlazeButton_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/design_MicroBlazeButton/ip/design_MicroBlazeButton_ilmb_bram_if_cntlr_0/design_MicroBlazeButton_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MicroBlazeButton_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_MicroBlazeButton_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/design_MicroBlazeButton/ip/design_MicroBlazeButton_lmb_bram_0/design_MicroBlazeButton_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MicroBlazeButton_lmb_bram_0 || ORIG_REF_NAME==design_MicroBlazeButton_lmb_bram_0} -quiet] -quiet

# IP: bd/design_MicroBlazeButton/ip/design_MicroBlazeButton_mdm_1_0/design_MicroBlazeButton_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MicroBlazeButton_mdm_1_0 || ORIG_REF_NAME==design_MicroBlazeButton_mdm_1_0} -quiet] -quiet

# IP: bd/design_MicroBlazeButton/ip/design_MicroBlazeButton_clk_wiz_1_0/design_MicroBlazeButton_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MicroBlazeButton_clk_wiz_1_0 || ORIG_REF_NAME==design_MicroBlazeButton_clk_wiz_1_0} -quiet] -quiet

# IP: bd/design_MicroBlazeButton/ip/design_MicroBlazeButton_rst_clk_wiz_1_100M_0/design_MicroBlazeButton_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MicroBlazeButton_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==design_MicroBlazeButton_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/design_MicroBlazeButton/ip/design_MicroBlazeButton_xbar_0/design_MicroBlazeButton_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MicroBlazeButton_xbar_0 || ORIG_REF_NAME==design_MicroBlazeButton_xbar_0} -quiet] -quiet

# IP: bd/design_MicroBlazeButton/ip/design_MicroBlazeButton_microblaze_0_axi_periph_0/design_MicroBlazeButton_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MicroBlazeButton_microblaze_0_axi_periph_0 || ORIG_REF_NAME==design_MicroBlazeButton_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_MicroBlazeButton/ip/design_MicroBlazeButton_axi_gpio_1_0/design_MicroBlazeButton_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MicroBlazeButton_axi_gpio_1_0 || ORIG_REF_NAME==design_MicroBlazeButton_axi_gpio_1_0} -quiet] -quiet

# XDC: bd/design_MicroBlazeButton/design_MicroBlazeButton_ooc.xdc
